### ISSUE TITLE
DescopeBaseUrl points to localhost

### ISSUE THREAD

**Issue by PyAgni** [descope/go-sdk#162]
https://github.com/descope/go-sdk/blob/dc158057b926c6b63bbb49c468e50b3ed142a3e1/examples/webapp/main.go#L42

`DescopeBaseURL` should probably point to `https://api.descope.com`, else it's not working locally.
Same for the `ginwebapp` example.

**Comment by dorsha** [comment]
Fixed.
Thanks @PyAgni!
