### ISSUE TITLE
Set tags / releases

### ISSUE THREAD

**Issue by lior-belugahealth** [descope/go-sdk#179]
Hi Guys,
Can you set tag / releases for the repo ?
This required for proper go.mod versioning

**Comment by dorsha** [comment]
Hi @lior-belugahealth, 

Of course, we are definitely going to add this soon.
Will keep you posted here.

Thanks for your feedback!

**Comment by aviadl** [comment]
Done
Here is the first release
https://github.com/descope/go-sdk/releases/tag/v0.9.0
