### ISSUE TITLE
ConfigureSettings required fields

### ISSUE THREAD

**Issue by chauhanshubham** [descope/go-sdk#293]
The `func (s *sso) ConfigureSettings` function mentions the `idpURL`, `idpCert`, `entityID` params as required.
Although, in the UI there is an option to configure SSO, either via metadata url or using the 3 params mentioned above.

These params being "required" is not helping us to configure just the `redirectURL` which is the
"Post Authentication Redirect URL" in UI.
I believe either the required checks should be relaxed, or the `SSO().ConfigureMetadata` function should help
to configure the `redirectURL` too?

**Comment by dorsha** [comment]
Thanks, you are correct.
We will fix this.

**Comment by dorsha** [comment]
@chauhanshubham as a workaround (very bad one), you can do the following:

`ConfigureSSOSettings` with fake values for `idpURL`, `idpCert` and `entityID` and real value for `redirectURL`.
and then immediately call:
`ConfigureSSOMetadata` to enable metadata back.
Again, this is not elegant, but a workaround so you won't be blocked until a **proper** fix.

**Comment by chauhanshubham** [comment]
Thanks for getting back and marking it as a bug.

> then immediately call:
ConfigureSSOMetadata to enable metadata back.

I see. so the ordering will ensure that the metadata way is activated?

**Comment by dorsha** [comment]
> Thanks for getting back and marking it as a bug.
> 
> > then immediately call:
> > ConfigureSSOMetadata to enable metadata back.
> 
> I see. so the ordering will ensure that the metadata way is activated?

Right.

**Comment by chauhanshubham** [comment]
Hey, has the fix for this pushed? Could you please attach a commit/PR so we can track it and the next release tag for it, so we can use the fix properly.

**Comment by shilgapira** [comment]
Hi! There were some backend changes that have already been merged for this fix, and there's also a [pending PR](https://github.com/descope/go-sdk/pull/296) for supporting this here in the `go-sdk`.

The backend changes need to go live first before you can use this in production though. I'll reopen this issue and close it again once everything is deployed and the fix is on the `main` branch here.

**Comment by chauhanshubham** [comment]
thanks for reopening and attaching the PR, it'll just help me track this externally.

**Comment by shilgapira** [comment]
@chauhanshubham The backend changes should be deployed now, and the SDK changea are part of the `1.5.4` tag. Let me know if there are any other issues 🙂
