### ISSUE TITLE
Auth.Logout using refreshToken directly?

### ISSUE THREAD

**Issue by Asaf51** [descope/go-sdk#434]
Currently there is Auth.Logout function which expects to get the request
I'd like a function that only gets the refresh token when the request is not in reach
I saw that the JS sdk does have a logout api using the refreshToken directly
Should it be added or am I missing somthing?
thanks

**Comment by dorsha** [comment]
Hi, 
We will look into adding that.
Until then, as a workaround, you can create a dummy request that includes the refreshToken, like this:
```
request := &http.Request{Header: http.Header{}}
request.AddCookie(&http.Cookie{Name: descope.RefreshCookieName, Value: refreshToken})
w := httptest.NewRecorder() // w is optional
err := a.Logout(request, w)
```
You can look at this test for example: https://github.com/descope/go-sdk/blob/ea6b9567677c373224b5487e7c9dfd5ee8b6c5bf/descope/internal/auth/auth_test.go#L625

**Comment by Asaf51** [comment]
Nice, thanks for the quick response and fix!
